version: '3.3'

services:
  backend:
    build: ./backend-service
    container_name: backend-service
    depends_on:
      - postgres
    ports:
      - 5000:5000

  postgres: 
    image: postgres:13.3
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin: 
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "al3406099@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "test_password"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports: 
      - 5050:80
    
  frontend:
    build: ./frontend-service
    container_name: frontend-service
    ports:
      - 3000:3000

volumes:
  postgres-data: 
  pgadmin-data:
